Courses table preview action
WalkMe/teachme-admin pull request #318
Opened 2020-09-15 15:25 UTC by nunibaranes

- Created components: `Modal` , `PreviewModal` and `PreviewCoursesButton`.

- `Modal` is a generic component, creating 'root-modal' DOM element next to app's 'root' element,  using ReactDOM.createPortal. 
- `PreviewModal` is rendering header and iframe to preview the selected items, (currently I'm rendering static url - the SDK is not ready )
- `PreviewCoursesButton` clicking on 'preview' button, manage local state to manage the modal and child behavior.
- Adding animation.
- commented the `PreviewCoursesButton` component. to prevent rendering the feature before is ready.

2020-09-16 07:37 UTC, dr15 requested changes
Please look at the comments I left

2020-09-16 07:37 UTC, dr15 commented on src/hooks/useWindowResize.tsx
> +  windowHeight: number;
Consider using `useEventListener` for the implementation of `useWindowResize`. Also consider using throttle on the event callback.

2020-09-16 07:37 UTC, dr15 commented on src/components/Screen/CoursesScreen/PreviewCoursesButton.tsx
> +  const [showModal, setModal] = useState(false);
Please change `setModal` to `setShowModal`

2020-09-16 07:37 UTC, dr15 commented on src/components/Screen/CoursesScreen/PreviewCoursesButton.tsx
> +  const onPreviewCourses = () => {
Please add `useCallback()` to any callback you pass to a child component

2020-09-16 07:37 UTC, dr15 commented on src/components/Layout/Modal/index.tsx
> +  const setGlobals = useCallback(() => {
When creating a function that is used within the same component there is no need to ass `useCallback()`, it is only necessary when passin it to a child component

2020-09-16 14:00 UTC, RonnyO commented on src/components/Layout/Modal/index.tsx
> +    }
Why not `containerEl?.classList.toggle(classes['is-open'], isOpen);`? See example [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#Examples).

2020-09-16 15:27 UTC, dvira commented on src/hooks/useWindowResize.tsx
> +  windowHeight: number;
We added a library (a prewritten hook) that does window size calculation with debounce. 
The `useEventListener` does not accept a condition for adding the event listener, so we kept this implementation for now, until we expand the hook's api.

2020-09-16 15:27 UTC, dvira commented on src/components/Screen/CoursesScreen/PreviewCoursesButton.tsx
> +  const [showModal, setModal] = useState(false);
Done

2020-09-16 15:27 UTC, dvira commented on src/components/Screen/CoursesScreen/PreviewCoursesButton.tsx
> +  const onPreviewCourses = () => {
Right, done.

2020-09-17 06:17 UTC, dr15 approved these changes
🔥

2020-09-17 06:21 UTC, merged