Check if Published Or Modified in all Envs
WalkMe/teachme-admin pull request #359
Opened 2020-10-05 18:57 UTC by zuberikfir

2020-10-05 22:57 UTC, chen-c-walkme commented on src/components/Screen/CoursesScreen/DeleteCoursesButton.tsx
> +  const cannotDelete = selectedRows.some((course: UICourse) => Object.values(course.publishStatuses)
*Please see Slack message about design changes for this task*
1. Ignore success environment in this check
2. Extract this check to a function, so it can be used to tell the customer what environments the course is published on, in a tooltip.

2020-10-06 08:45 UTC, dr15 requested changes
- I asked a couple of questions because I seem to be missing some information.
- Please use the conventions that are already in use in this repo. Always commit with git hooks. If you think we should start using git flow let's have a discussion about it before using it.

2020-10-06 08:45 UTC, dr15 commented on src/components/Screen/Playground/components/Dialogs.tsx
> +            publishStatuses : {0 : 1},
Could you explain this line?
Also, i'm pretty sure prettier/eslint would prefer it looks like this: `publishStatuses: { 0: 1 },`. Please commit using git hooks.

2020-10-06 08:45 UTC, dr15 commented on src/components/Screen/CoursesScreen/DeleteCoursesButton.tsx
> +  const cannotDelete = selectedRows.some((course: UICourse) => Object.values(course.publishStatuses)
I think I am missing something, there's the code that was added in `src/walkme/data/courseMetadata.ts` that seems to be doing the same thing? Why not use that?

2020-10-06 10:59 UTC, chen-c-walkme commented on src/walkme/data/courseMetadata.ts
> +    env as unknown as EnvironmentType !== EnvironmentType.Test &&
Why Test?

2020-10-06 12:39 UTC, chen-c-walkme approved these changes

2020-10-07 06:38 UTC, merged