Test Modal
WalkMe/teachme-admin pull request #380
Opened 2020-10-11 11:25 UTC by dr15

- Adds test for the `Modal` component.
- Updates The component to make sure there is always an element to attach to.

2020-10-11 12:38 UTC, dvira requested changes
Looks good! I had a few minor comments.
Please provide a screenshot of the updated coverage if you can.

2020-10-11 12:38 UTC, dvira commented on src/components/Layout/Modal/Modal.test.tsx
> +      await userEvent.type(modalRoot, '{esc}');
You don't need the `await` or the `async` in this or any other test.

2020-10-11 12:38 UTC, dvira commented on src/components/Layout/Modal/Modal.test.tsx
> +    expect(modal).toHaveTextContent('modal content');
While this is correct, it is considered best practice to use `getByText` and then explicitly assert that it is rendered, i.e.:
`const modal = screen.getByText('modal-content');
expect(modal).toBeInTheDocument();`.

2020-10-11 12:38 UTC, dvira commented on src/components/Layout/Modal/Modal.test.tsx
> +    const onCloseCallback = jest.fn();
I suggest shorting this to 'onClose' just for better readability.
Please do NOT move this mock outside though, as you're using it in different tests and by moving it you would lose its contained reference (meaning you would call this **at least** once).

2020-10-11 12:38 UTC, dvira commented on src/components/Layout/Modal/Modal.test.tsx
> +type ITestModalProps = Omit<IModal, 'children'>;
Not that important, but still was wondering, didn't we agree on some convention regarding naming props? I think it was prefix with `I` and no suffix.

2020-10-12 06:22 UTC, dr15 commented on src/components/Layout/Modal/Modal.test.tsx
> +type ITestModalProps = Omit<IModal, 'children'>;
As far as I know it's both

2020-10-12 06:22 UTC, dr15 commented on src/components/Layout/Modal/Modal.test.tsx
> +      await userEvent.type(modalRoot, '{esc}');
Fixed

2020-10-12 06:22 UTC, dr15 commented on src/components/Layout/Modal/Modal.test.tsx
> +    expect(modal).toHaveTextContent('modal content');
Fixed

2020-10-12 06:48 UTC, dr15 commented on src/components/Layout/Modal/Modal.test.tsx
> +    const onCloseCallback = jest.fn();
Ok

2020-10-12 06:57 UTC, dvira approved these changes

2020-10-12 07:43 UTC, merged