Add new quiz flow - unit test
WalkMe/teachme-admin pull request #394
Opened 2020-10-18 18:34 UTC by nunibaranes

2020-10-19 07:03 UTC, dr15 requested changes
Left a few comments

2020-10-19 07:03 UTC, dr15 commented on src/components/Screen/CourseEditorScreen/QuizSettingsForm/QuizSettingsForm.test.tsx
> +  it('should change quiz.forceCourseCompletion default data to true', () => {
Maybe try wording it in a way that explains what the user tried to do

2020-10-19 07:03 UTC, dr15 commented on src/components/Screen/CourseEditorScreen/__tests__/CourseOutlineQuizFlow.test.tsx
> +    describe('quiz settings', () => {
I would reconsider nesting tests

2020-10-21 06:19 UTC, dr15 requested changes
I  have a few questions

2020-10-21 06:19 UTC, dr15 commented on src/components/Screen/CourseEditorScreen/__tests__/CourseOutlineQuizFlow.test.tsx
> +  it("quiz settings - enable/disable enable quiz switch field should effect quiz's title", async () => {
I think there's an extra 'enable' in the title

2020-10-21 06:19 UTC, dr15 commented on src/components/Screen/CourseEditorScreen/QuizSettingsForm/QuizSettingsForm.test.tsx
> +    const randQuestions = getSwitchByClosestSelector('.random-questions');
I couldn't find where/how this class is added

2020-10-21 06:36 UTC, nunibaranes commented on src/components/Screen/CourseEditorScreen/__tests__/CourseOutlineQuizFlow.test.tsx
> +  it("quiz settings - enable/disable enable quiz switch field should effect quiz's title", async () => {
You right :) thanks

2020-10-21 06:38 UTC, nunibaranes commented on src/components/Screen/CourseEditorScreen/QuizSettingsForm/QuizSettingsForm.test.tsx
> +    const randQuestions = getSwitchByClosestSelector('.random-questions');
This class exist in `QuizSettingsForm/index.tsx`. (line 76) :)
I added to each `FormGroup` className.

2020-10-25 13:55 UTC, closed without merging