Feature/ar 117 courses screen layout
WalkMe/teachme-admin pull request #475
Opened 2020-12-20 17:40 UTC by yuvallevanoni

2020-12-21 15:26 UTC, dvira requested changes
Looks good!
Left a few comments.

2020-12-21 15:26 UTC, dvira commented on src/components/Screen-v2/CoursesScreen/index.tsx
> +    isDrawerVisible,
Why do you need this inside context?
Looks like `useState` would have the same effect, since the scope is limited to only this file.
We use context when we need to share state between 2 or more components.
If this is something you are planning then leave it, else, please replace it.

2020-12-21 15:26 UTC, dvira commented on src/components/Screen-v2/CoursesScreen/index.tsx
> +        <div className={cc([!isDrawerVisible ? styles.isCollapsed : '', styles.sideDrawer])}>
You're misusing `classcat` here. You want to do this:
```
className={cc([{ [styles.isCollapsed]: !isDrawerVisible }, styles.sideDrawer])
```

2020-12-21 22:36 UTC, yuvallevanoni commented on src/components/common-v2/AnalyticsCharts/style.module.scss
> +
notice I added this comment here

2020-12-23 15:20 UTC, dvira approved these changes
Awesome!!
Approved with a few minor comments.

2020-12-23 15:20 UTC, dvira commented on src/components/Screen-v2/CoursesScreen/CoursesList.tsx
> +  //Courses will appear to your users in the order below. Drag & Drop items to change their order.
Is this comment necessary?

2020-12-23 15:20 UTC, dvira commented on src/components/Screen-v2/CoursesScreen/CoursesList.tsx
> +    <div className={cc([className])}>
No need for `cc`.

2020-12-23 15:20 UTC, dvira commented on src/components/Screen-v2/CoursesScreen/style.module.scss
> +  }
Why change the color of the header here?
If it's a required design change it should be made in `wm-ui` repo, so it affects all tables across the app.
BTW, always prefer css-vars over hard-coded colors.

2020-12-23 15:20 UTC, dvira commented on src/components/Screen-v2/CoursesScreen/tableData.tsx
> +  // },
Please add a comment explaining why you commented this out, and if necessary a `TODO`.

2020-12-23 15:20 UTC, dvira commented on src/components/common-v2/AnalyticsCharts/index.tsx
> +      <div className={cc([classes.graphs])}>
No need for `cc` here.

2020-12-23 15:20 UTC, dvira commented on src/components/Screen-v2/CoursesScreen/index.tsx
> +import cc from 'classcat';
Please add a line break here.

2020-12-23 15:20 UTC, dvira commented on src/components/Screen-v2/CoursesScreen/index.tsx
Please remove this line break.

2020-12-23 17:38 UTC, merged