Implement wm list item
WalkMe/teachme-admin pull request #495
Opened 2020-12-29 14:44 UTC by nunibaranes

- Implements WMListItem in`TaskItem`.
- Removes `I` prefix from interfaces
- Adding/fixing WMListItem styles in lesson/quiz containers.  

TODO:
fixing dropPreview margins

2020-12-29 16:26 UTC, dvira requested changes
Looks good, left some comments.

2020-12-29 16:26 UTC, dvira commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseOutlineTab/CourseOutlineQuiz/index.tsx
> +          className={cc([classes.lastQuizListItem])}
No need for `classcat` here.

2020-12-29 16:26 UTC, dvira commented on src/components/Screen-v2/CourseEditorScreen/ResourceList/ResourceItemList/index.tsx
> +} => {
Could be `VirtualizationProps` instead of this object right?

2020-12-29 16:26 UTC, dvira commented on src/components/Screen-v2/CourseEditorScreen/common/TaskItem/index.tsx
> +  DotType,
I know this is off-topic but shouldn't this be `WMDotType`?

2020-12-29 16:26 UTC, dvira commented on src/components/Screen-v2/CourseEditorScreen/common/TaskItem/index.tsx
>    );
Both callbacks' event types should be `MouseEvent` (imported from 'react') instead of 'any'.

2020-12-29 16:26 UTC, dvira commented on src/components/Screen-v2/CourseEditorScreen/common/TaskItem/index.tsx
> +      extraActions={actions}
I think you can use `allActions` directly in here.

2020-12-29 16:39 UTC, dr15 requested changes
Left a couple of comments

2020-12-29 16:39 UTC, dr15 commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseOutlineTab/CourseOutlineQuiz/CourseQuestionList.tsx
> +        items.some((item, i) => i === items.length - 1 && activeQuestionId === item.id),
I think this can be done without a loop

2020-12-29 16:39 UTC, dr15 commented on src/components/Screen-v2/CourseEditorScreen/common/TaskItem/index.tsx
> +  const deleteBtnProps = {
Consider wrapping all consts with `useMemo()` but make sure this doesn't create bugs with SDK state (for example when reordering items)

2020-12-29 16:39 UTC, dr15 commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseOutlineTab/CourseItemsList/index.tsx
> +      setLastItemIsActive(() => items.some((item, i) => i === items.length - 1 && isActive(item)));
Please see previous comment

2020-12-29 18:07 UTC, nunibaranes commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseOutlineTab/CourseItemsList/index.tsx
> +  taskItemPropstaskItemProps?: any;
Hahaha I fixed it, my mistake...

2020-12-29 18:15 UTC, nunibaranes commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseOutlineTab/CourseOutlineList/style.module.scss
> +  --marginSize: 24px;
I fixed it, I'm using it now for other components

2020-12-29 18:40 UTC, nunibaranes commented on src/components/Screen-v2/CourseEditorScreen/common/TaskItem/index.tsx
> +  DotType,
it should be, but this is how it called in `wm-ui-components`

2020-12-29 19:24 UTC, nunibaranes commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseOutlineTab/CourseItemsList/index.tsx
> +      setLastItemIsActive(() => items.some((item, i) => i === items.length - 1 && isActive(item)));
Here I couldn't use without a loop, but I used `useMemo` instead of `useEffect`.

2020-12-30 09:39 UTC, dvira approved these changes
Looks AMAZING!
Left you some notes as requested.

2020-12-30 09:39 UTC, dvira commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseOutlineTab/CourseOutlineList/style.module.scss
>    background-color: var(--hover-color-translucent);
I suggest you replace these css vars with those of `wm-ui`

2020-12-30 09:39 UTC, dvira commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseOutlineTab/CourseOutlineQuiz/style.module.scss
> +  + .quizListItem .item:not(.cardGhost) {
Instead of nesting you could write it all in one line

2020-12-30 11:37 UTC, merged