Tm os integration
WalkMe/teachme-admin pull request #501
Opened 2020-12-31 12:16 UTC by zuberikfir

2021-01-03 14:08 UTC, dvira requested changes

2021-01-03 14:08 UTC, dvira commented on src/utils/app-utils.ts
> +
Not sure what was your intention with this, care to explain?

2021-01-04 07:55 UTC, zuberikfir commented on src/hooks/useShellOS.ts
> +  }, [environments]);
removed

2021-01-04 07:57 UTC, zuberikfir commented on src/images/os/course_icon.svg
> +</svg>
yes. we need them for the OS side bar links

2021-01-04 07:58 UTC, zuberikfir commented on src/utils/app-utils.ts
> +
removed

2021-01-04 10:40 UTC, dvira approved these changes
NOICE!

2021-01-04 11:41 UTC, merged