Applies table exact widths in expanded view according to design
WalkMe/teachme-admin pull request #506
Opened 2021-01-03 11:40 UTC by yuvallevanoni

- Adds paddings + widths + maxWidths
- Fixes sidebar width

2021-01-03 11:44 UTC, yuvallevanoni commented on src/components/common/Logo/style.module.scss
> +  padding: 18px 0 0 7px;
This change is so the overall width of the table will be 1760px according to design (and entire screen is 1920px).
The sidebar itself should change in a different PR, so this is only a minor adaptation

2021-01-03 11:48 UTC, yuvallevanoni commented on src/styles/variables.scss
> -  --sidebar-width: 110px;
This change is so the overall width of the table will be 1760px according to design (and entire screen is 1920px).
The sidebar itself should change in a different PR, so this is only a minor adaptation

2021-01-04 08:03 UTC, dr15 requested changes
I checked it on my screen which is 1920px and there is a horizontal scrollbar that I think should not be there?

2021-01-04 08:03 UTC, dr15 commented on src/components/common/Logo/style.module.scss
> +  padding: 18px 0 0 7px;
This will change the logo for the old design too. Is that what you were going for?

2021-01-04 13:05 UTC, yuvallevanoni reviewed
I created new v2 folders for:
- layout -> sidebar
- layout -> headerToolBar

This can be used as the root for later tickets regarding the new design for these layout components

2021-01-04 13:05 UTC, yuvallevanoni commented on src/components/Layout/Sidebar-v2/Navigation/Navigation.test.tsx
> +import React from 'react';
Exact copy from the Sidebar.
Only Sidebar-v2/style.module.scss has changed

2021-01-04 13:05 UTC, yuvallevanoni commented on src/components/Layout/Sidebar-v2/style.module.scss
> +  width: var(--sidebar-width-v2);
First change

2021-01-04 13:05 UTC, yuvallevanoni commented on src/components/Layout/Sidebar-v2/style.module.scss
> +  width: var(--sidebar-width-v2);
second change

2021-01-04 13:05 UTC, yuvallevanoni commented on src/components/common-v2/Logo/style.module.scss
> +  padding: 18px 0 0 7px;
Changed from 21px to 7px for padding-left

2021-01-05 12:31 UTC, closed without merging