Image settings v2
WalkMe/teachme-admin pull request #513
Opened 2021-01-07 09:19 UTC by dr15

Note: This only changes the content of the image settings section. It does not restyle the entire setting box - so the background is the wrong color, and other differences might be found too.

2021-01-07 12:54 UTC, nunibaranes commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseSettingsTab/ImageSettings/ImageThumbnails.tsx
> +        <div className={cc([styles['thumbnail-wrapper'], { [styles.loading]: uploadingImages }])}>
Please replace all the kabab-case to camel-case className

2021-01-07 12:57 UTC, nunibaranes commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseSettingsTab/ImageSettings/style.module.scss
>        color: var(--white);
I'd consider to replace it to `--wmwhite`

2021-01-07 13:02 UTC, nunibaranes commented on src/components/common/WMDropzoneStateBox/ActiveDragAction.tsx
> +        <Icon className={classes['upload-icon']} type={IconType.UploadFile} />
Pay attention, you changed the common `WMDropzoneStateBox`, you should clone the component to common-2 and make the changes on the cloned component

2021-01-07 13:10 UTC, nunibaranes requested changes
Left a couple of comments.
Please clone the `WMDropzoneStateBox` to common-2, and revert the changes to `WMDropzoneStateBox` in common.

2021-01-07 13:13 UTC, nunibaranes commented on src/components/common/WMDropzoneStateBox/ActiveDragAction.tsx
> +        <Icon className={classes['upload-icon']} type={IconType.UploadFile} />
Dvir Adding the icon to `wm-ui`, it will be available on version 0.1.63

2021-01-10 11:54 UTC, dr15 commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseSettingsTab/ImageSettings/ImageThumbnails.tsx
> +        <div className={cc([styles['thumbnail-wrapper'], { [styles.loading]: uploadingImages }])}>
Fixed

2021-01-10 11:59 UTC, dr15 commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseSettingsTab/ImageSettings/style.module.scss
>        color: var(--white);
Fixed

2021-01-11 06:14 UTC, dr15 commented on src/components/common/WMDropzoneStateBox/ActiveDragAction.tsx
> +        <Icon className={classes['upload-icon']} type={IconType.UploadFile} />
Fixed

2021-01-11 06:14 UTC, dr15 commented on src/components/common/WMDropzoneStateBox/ActiveDragAction.tsx
> +        <Icon className={classes['upload-icon']} type={IconType.UploadFile} />
Thanks!

2021-01-11 07:48 UTC, nunibaranes commented on src/components/Screen-v2/CourseEditorScreen/CourseOutline/CourseSettingsTab/ImageSettings/ImageThumbnails.tsx
> +              { [styles['loading']]: uploadingImages },
You can remove the usages in object literal (`styles['loading']`)

2021-01-11 07:49 UTC, nunibaranes commented on src/components/common-v2/WMDropzoneStateBox/DropzoneErrorBox.tsx
> +      <div className={cc([classes['image-upload-error'], classes['action']])}>
Also here, if you can please remove the usages with object literal

2021-01-11 07:59 UTC, nunibaranes approved these changes
I left a few comments.
Looks good, great job!!

2021-01-11 08:50 UTC, merged