Sets background color of selected rows while drag&dropping
WalkMe/teachme-admin pull request #525
Opened 2021-01-12 20:32 UTC by yuvallevanoni

- to stay the same

2021-01-12 20:48 UTC, yuvallevanoni commented on src/components/common-v2/SortableTable/index.tsx
The same logic exists in the old WMTable

2021-01-12 20:49 UTC, yuvallevanoni commented on src/components/Screen-v2/CoursesScreen/style.module.scss
> +
selected row will not change background while drag&drop

2021-01-14 16:23 UTC, nunibaranes commented on src/components/Screen-v2/CoursesScreen/style.module.scss
> +            }
Please add styles for selectedRow while dragging.

2021-01-14 16:24 UTC, nunibaranes requested changes
Looks great, please see my comment :)

2021-01-14 18:04 UTC, yuvallevanoni commented on src/components/Screen-v2/CoursesScreen/style.module.scss
> +            }
in row 328

2021-01-17 09:50 UTC, nunibaranes approved these changes
Good job :) 
Approved!

2021-01-17 09:51 UTC, merged